language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE test_byob;' -U postgres
notifications:
  email: false
deploy:
  api_key:
    secure: sXyKXyrNfG723RHxuSpCYhoT0dbN4/r65sqNxR8x4qk5aDlQV96ilNUexuoiq3Zydk8sqw9ZUeN799bmklc3s90YY62uA27qRCiCJOaPisy/aWiEJR6SlSVicGu4yETj1H7rRz7q6rbmi7Jx55+CxHyyt6aATbGXw4HkPwh3/5aCEfp9DugGsC8Jkky6Gv8UUztv4RbJZWK45EzXrHbLvRVI0mivyUSioa+FOlPmfmuyL6Ufw400cfCWq07EJVGyfuZZKO0PSpsbPv01MGhorEUVPrEvWMFlKjsTpQ90HjxLxw7m8nrThlzWvgalQvX/Kiq4XP4eYJJ8kyTZAH/6H/5RNwPtycBrFtU9DqyJTgPjWVwJ/lg5/E5P8QCnx0lPbg49S3ICgboPxn+9X/7M5TbKQhSrWV4Rp77YPbT3Mf0uX0Zm2SIZ7N1npDkV2qIoLfSfT8Z0S2psJb2UnPrXzNlAlCwrn+yQ1dR4KqApfyDRGtjUztXRHizeM7PwXu/QVdXK0+c7DbiRQs0lSQk5OidyX3ml7mFKVFlcdY/dyH9n1aPs2mCAo0MnKg8vBhIQCVWDPpx1pDyWDi3RzLe7eVjV81Mv53B311hgN5QZ0MJMuzqOy7eDz0vrior/r6VN/e+7PIJK4rRDzdhasjC+iVJIwcct6yVWERUPcQvGHDw=
app: nba-api-byob
skip_cleanup: true
